### ISSUE TITLE
Peer-To-Peer Review (Guys, you can write here your comments.)

### ISSUE THREAD

**Issue by tacettinkustu** [tacettinkustu/My-Portfolio-Website#11]

**Comment by toliboff** [comment]
- Make elements fit the screen size. In 1024px screen width, some elements go beyond the screen.

**Comment by tacettinkustu** [comment]
> * Make elements fit the screen size. In 1024px screen width, some elements go beyond the screen.

Thank you for feedbacks Toliboff.
